version: "3.8"

services:
  cantaloupe:
    build: .
    image: cantaloupe:5.0.7
    ports:
      - "8182:8182"
    volumes:
      - ../web/images:/images
    command: >
      java
      -Dcantaloupe.config=cantaloupe.properties
      -Xmx2g
      -jar cantaloupe-5.0.7.jar
